# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
cache: cocoapods
podfile: Example/Podfile

env:
  global:
    - secure: "CoJ+Rhr6e2aNaPCyFGXSYiDsOPamS+Qy8l1B6HJlWFvBdhlAv/K4KaVzlCl75PNfoMgpIfd47J4ZSm7/+HjoyRg4bA/y92ZGNihULliPYzDmM+i4qWi2wzqWsv+y3fuJJGsgMnHdnPQvlzBiS0XEoTeJ4zeX5UxfS/6YFB591zPR/AO9HO5sTLqaxXVtcTnrDs/S9zgiltBp5VGMtskCkLc2qON3DMvqnqBwYyVH2kjJO8eeEKZWmUSIi0xM4+Z5zZi4qZmqTl8XdlOvzbDOUtJLSBWhwaASo7UgJggu47ok0Ze3Q/E+JzouDOv/VUtib6T35+rriAnepdWt9UFNrWZRrMZYvNsDisr744UjFlTvoc0GRn+vHS6EnAd4qZjwBJXBLOAEmFVOl1hLsAFtVvFs3am3vMytpcRbf0wcrXb9GXlg6yZVurlnDX7PxVKrmUI5Qo65OtZiJW6drYq1Qku3r4iYsevz864Sio/O9iPcKH3HfnoHLSX7MkdKC0GnNJbyWw9v/UVkKqvsPGMS68Qp8DwS2fnOUPGswLvFVMEKNO3Pa2BXG81LMDlgjFhMUhWD/caPrCKVsWNTjJoCRj2ZKqtR2C4gbdwfYY1wuer7zOsz428V/coVpN7UyQUxCug+9AKkAII2kti+gDyvzkct5uUM9wTbI85JBxjlc6c="
    - secure: "q5Jqt42qNuNMqUVFs4/Mdwd/WErEsKWaF7kGhbQQ3a9LEkHn199c8/T2OZhc8Xj+OAt+whr7ojVcvgymAhs0BiY2fzmnwgl9QTZUb8pu0zZrYJvspz1mdUmAvoSqDkkwuiitphHeoz5AnNB1R8EVJxV8P93kx91K7hnsRvNZhif/auLf6bW8aFKV0DhvTQiLbcpBeUvKBNXN6uCAtfd5fbn/naelj479vRaWa+0i/YZLbgEBoIGyR9VOIMXBCscS2R5kBOPrBXzfST2YOUawzKVwOJfke8fO0A/W6whSBHJG0ASln9gcgS9ylx0BXyKMjLpOCU/Ey5vFAfgl33ni5OfGkJ6fZEnxmFe8ib3CGhjViBGT5fKOn4jZG7fCGcrsVmF8kmBsCuk6FoRUv7H5o4MVY+YXRQJPE0mqUwS5LVoHF9rexHsdDkgCSgQQLhScTBMKEEWuV36yCVm/+LgNSXkG7oWys4PPqpGqjYfN7ipdoRxRdLEiBuL09wUKmx2sdcFzW1TtVr/a/xQdKM6BiY7IH71b82Kn9y/YK0Hp5Mnxmquc3piy31VT0nSJrInOiq6A/v54zSZ2AS2fInPrC+TdVYBk3fsiqg0PrXGWRmQ41BaB0ga7q+wfPKueQw4iJdbKHbdgGLWFwIgGGSqE66B6d/XHj3OpnGSrC1MoHBs="
    - UPLOAD_IOS_SNAPSHOT_BUCKET_NAME=feedvc-failures
    - UPLOAD_IOS_SNAPSHOT_BUCKET_PREFIX=results
    - AWS_ACCESS_KEY_ID=ACCESS_KEY
    - AWS_SECRET_ACCESS_KEY=SECRET_KEY
    - AWS_REGION=us-west-2

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- gem install second_curtain
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/FeedCollectionViewController.xcworkspace -scheme FeedCollectionViewController-Example -sdk iphonesimulator10.2 -destination platform='iOS Simulator',OS=10.1,name='iPhone SE' ONLY_ACTIVE_ARCH=NO | second_curtain | xcpretty
- pod lib lint --allow-warnings
