# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
env:
- FB_REFERENCE_IMAGE_DIR=$(SOURCE_ROOT)/Tests/ReferenceImages
- IMAGE_DIFF_DIR=$(SOURCE_ROOT)/Tests/FailureDiffs
script:
- set -o pipefail && xcodebuild test -workspace Example/FeedCollectionViewController.xcworkspace -scheme FeedCollectionViewController-Example -sdk iphonesimulator10.2 -destination platform='iOS Simulator',OS=10.1,name='iPhone SE' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
